language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - tip
  
services:
  - memcache
  - redis-server

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
